version: '3'

services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: backend-container
    ports:
      - "8000:8000"
    volumes:
      - ../backend/app:/app
    networks:
      - app-network
    depends_on:
      - frontend

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: frontend-container
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
    networks:
      - app-network
    env_file:
      - .env
    environment:
      - HOST_NAME=${HOST_NAME}
      - DROP_BOX_ACCESS_TOKEN=${DROP_BOX_ACCESS_TOKEN}

networks:
  app-network:
    driver: bridge